language: node_js
node_js:
- 6
install: npm install
script: npm run build

deploy:
  
  - provider: pages
    repo: stanvishne/locations
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
      branch: master
  
  - provider: npm
    email: stanvishne@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
      repo: stanvishne/locations
